### ISSUE TITLE
Please add null-safety

### ISSUE THREAD

**Issue by gordonlotter** [rIIh/expandable-bottom-bar#17]
Please add a null-safety version. Great package just need to be upgraded to null-safety. Thanks.

**Comment by VrajGohil** [comment]
#18 Please check, I've tried migrating the package.

**Comment by AlexBolot** [comment]
@VrajGohil Can you publish your null-safe version on pub.dev ? This github repo seems unmaintained.
You can publish it and reference credit to this repo

**Comment by VrajGohil** [comment]
> @VrajGohil Can you publish your null-safe version on pub.dev ? This github repo seems unmaintained.
> You can publish it and reference credit to this repo

Sure I'll try and post it here.

**Comment by VrajGohil** [comment]
> @VrajGohil Can you publish your null-safe version on pub.dev ? This github repo seems unmaintained.
> You can publish it and reference credit to this repo

I'm still learning, but have published it here: https://pub.dev/packages/expandable_bottom_bar_new

**Comment by AlexBolot** [comment]
Thank you 🙂

**Comment by melvspace** [comment]
Please see new version 2.0.1 in pub.dev. Sorry for lateness.

**Comment by melvspace** [comment]
If you encounter any error feel free to open an issue. I will try to look at repo time by time.
