### ISSUE TITLE
from top to bottom

### ISSUE THREAD

**Issue by pishguy** [rIIh/expandable-bottom-bar#2]
is any option to change direction top openin from top to bottom?

**Comment by melvspace** [comment]
It's need some research and extra code
I'll try to done this feature later, but if you have any ideas to achieve this feel free to share

**Comment by melvspace** [comment]
Made some workaround, but need figure out how to get appbar overlap body content of scaffold
<img src="https://user-images.githubusercontent.com/19855397/58478861-b4667300-815f-11e9-9853-92f595a8b049.gif" alt="top-bar" height="700"/>

**Comment by pishguy** [comment]
best idea for this implementation

https://github.com/wunderlist/android-sliding-layer-lib

**Comment by melvspace** [comment]
Closing issue due to no one is in interest
