### ISSUE TITLE
avoid scrolling body of Scaffold

### ISSUE THREAD

**Issue by pishguy** [rIIh/expandable-bottom-bar#4]
when i add body to `Scaffold`, after opening bottom bar with TextField inside `expandable-bottom-bar`, and click on text field, that cause of scrolling `body` content, how can i resolve that?

for example

```
child: Scaffold(
  resizeToAvoidBottomPadding: true,
  backgroundColor: Theme.of(context).canvasColor,
  extendBody: true,
  body: Stack(children: <Widget>[Center(child: Text('aaaaa'))]),
```

**Comment by moyosolaa** [comment]
How did you solve this?
