### ISSUE TITLE
problem on change orientation

### ISSUE THREAD

**Issue by pishguy** [rIIh/expandable-bottom-bar#5]
http://s6.uplod.ir/i/00953/4fso99howgk2.jpg

http://s6.uplod.ir/i/00953/16ik446fbozc.jpg

**Comment by Tyxz** [comment]
Just a guess, but maybe the issue is with the position of your FAB? I think the notch of the bottom bar is based on the position of the FAB. Thus, this plugin does not handle it. You could try to define it in your Scaffold: 
```dart
Scaffold(
  floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
)
```
