### ISSUE TITLE
How to close expanded body on main body tap?

### ISSUE THREAD

**Issue by nidhi1612** [rIIh/expandable-bottom-bar#9]
Hello,

I am new to flutter. I have used expanded bottom app bar, i want to close the expanded body when user taps in the outside area. However i dont know how it can be done.

What exactly should be detected in order to close the pulled up expanded bottom bar?

**Comment by arnemolland** [comment]
You could add a GestureRecognizer to the outside area, and call `close` on your `BottomBarController`, for example:
```dart
DefaultBottomBarController(
  child: Scaffold(
    body: GestureDetector(
      onTap: DefaultBottomBarController.of(context).close,
      ... 
    ),
    bottomNavigationBar: BottomExpandableAppBar(
	... 
    ),
  ),
);
```

**Comment by melvspace** [comment]
Closing. Good answer provided
